#include <iostream>
#include <iomanip>
#include <limits>

using namespace std;

int main() {
    int i = 4;
    double d = 4.0;
    string s = "HackerRank ";

    int temp1;
    double temp2;
    string temp3;

    cin>>temp1>>temp2;
    cin.ignore(); // to remove the end of line character generated by cin
    getline(cin,temp3);

    cout<<temp1+i<<endl;
    cout<<fixed << setprecision(1)<<d+temp2<<endl;
    cout<<s<<temp3<<endl;

    // Declare second integer, double, and String variables.

    // Read and save an integer, double, and String to your variables.
    // Note: If you have trouble reading the entire string, please go back and review the Tutorial closely.

    // Print the sum of both integer variables on a new line.

    // Print the sum of the double variables on a new line.

    // Concatenate and print the String variables on a new line
    // The 's' variable above should be printed first.

    return 0;
}
